[options]
proxy_mode = True
server_name = retousj.es
logfile = /etc/odoo/odoo.log
limit_memory_hard = 1677721600
limit_memory_soft = 629145600
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
workers = 8
addons_path = /mnt/extra-addons